# scale-config.yml:
#   Powers what instance types are available for GHA auto-scaled
#   runners. Runners listed here will be available as self hosted
#   runners, configuration is directly pulled from the main branch.
#
# NOTE (Apr, 5, 2021): Linux runners are currently all an amazonlinux2
#
# TODO: Add some documentation on how the auto-scaling works
#
# NOTE: Default values,
#
# runner_types:
#   runner_label:
#     instance_type: m4.large
#     os: linux
#     max_available: 20
#     disk_size: 50

runner_types:
  linux.2xlarge:
    instance_type: c5.2xlarge
    os: linux
    max_available: 500
    disk_size: 150
  linux.8xlarge.nvidia.gpu:
    instance_type: g3.8xlarge
    os: linux
    max_available: 50
    disk_size: 150
  windows.4xlarge:
    instance_type: c5.4xlarge
    os: windows
    max_available: 200
    disk_size: 256
